import { MeasurePercentiles } from "../model";

export const ChestPressPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 1.48
        }, {
          percentile: 80,
          value: 1.32
        }, {
          percentile: 70,
          value: 1.22
        }, {
          percentile: 60,
          value: 1.14
        }, {
          percentile: 50,
          value: 1.06
        }, {
          percentile: 40,
          value: 0.99
        }, {
          percentile: 30,
          value: 0.93
        }, {
          percentile: 20,
          value: 0.88
        }, {
          percentile: 10,
          value: 0.8
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 1.24
        }, {
          percentile: 80,
          value: 1.12
        }, {
          percentile: 70,
          value: 1.04
        }, {
          percentile: 60,
          value: 0.98
        }, {
          percentile: 50,
          value: 0.93
        }, {
          percentile: 40,
          value: 0.88
        }, {
          percentile: 30,
          value: 0.83
        }, {
          percentile: 20,
          value: 0.78
        }, {
          percentile: 10,
          value: 0.71
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 1.1
        }, {
          percentile: 80,
          value: 1
        }, {
          percentile: 70,
          value: 0.93
        }, {
          percentile: 60,
          value: 0.88
        }, {
          percentile: 50,
          value: 0.84
        }, {
          percentile: 40,
          value: 0.8
        }, {
          percentile: 30,
          value: 0.76
        }, {
          percentile: 20,
          value: 0.72
        }, {
          percentile: 10,
          value: 0.65
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 0.97
        }, {
          percentile: 80,
          value: 0.9
        }, {
          percentile: 70,
          value: 0.84
        }, {
          percentile: 60,
          value: 0.79
        }, {
          percentile: 50,
          value: 0.75
        }, {
          percentile: 40,
          value: 0.71
        }, {
          percentile: 30,
          value: 0.68
        }, {
          percentile: 20,
          value: 0.63
        }, {
          percentile: 10,
          value: 0.57
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 0.89
        }, {
          percentile: 80,
          value: 0.82
        }, {
          percentile: 70,
          value: 0.77
        }, {
          percentile: 60,
          value: 0.72
        }, {
          percentile: 50,
          value: 0.68
        }, {
          percentile: 40,
          value: 0.66
        }, {
          percentile: 30,
          value: 0.63
        }, {
          percentile: 20,
          value: 0.57
        }, {
          percentile: 10,
          value: 0.53
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 0.9
        }, {
          percentile: 80,
          value: 0.8
        }, {
          percentile: 70,
          value: 0.74
        }, {
          percentile: 60,
          value: 0.7
        }, {
          percentile: 50,
          value: 0.65
        }, {
          percentile: 40,
          value: 0.59
        }, {
          percentile: 30,
          value: 0.56
        }, {
          percentile: 20,
          value: 0.51
        }, {
          percentile: 10,
          value: 0.48
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 0.76
        }, {
          percentile: 80,
          value: 0.7
        }, {
          percentile: 70,
          value: 0.63
        }, {
          percentile: 60,
          value: 0.6
        }, {
          percentile: 50,
          value: 0.57
        }, {
          percentile: 40,
          value: 0.53
        }, {
          percentile: 30,
          value: 0.51
        }, {
          percentile: 20,
          value: 0.47
        }, {
          percentile: 10,
          value: 0.42
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 0.71
        }, {
          percentile: 80,
          value: 0.62
        }, {
          percentile: 70,
          value: 0.57
        }, {
          percentile: 60,
          value: 0.54
        }, {
          percentile: 50,
          value: 0.52
        }, {
          percentile: 40,
          value: 0.5
        }, {
          percentile: 30,
          value: 0.47
        }, {
          percentile: 20,
          value: 0.43
        }, {
          percentile: 10,
          value: 0.38
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 0.61
        }, {
          percentile: 80,
          value: 0.55
        }, {
          percentile: 70,
          value: 0.52
        }, {
          percentile: 60,
          value: 0.48
        }, {
          percentile: 50,
          value: 0.46
        }, {
          percentile: 40,
          value: 0.44
        }, {
          percentile: 30,
          value: 0.42
        }, {
          percentile: 20,
          value: 0.39
        }, {
          percentile: 10,
          value: 0.37
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 0.64
        }, {
          percentile: 80,
          value: 0.54
        }, {
          percentile: 70,
          value: 0.51
        }, {
          percentile: 60,
          value: 0.47
        }, {
          percentile: 50,
          value: 0.45
        }, {
          percentile: 40,
          value: 0.43
        }, {
          percentile: 30,
          value: 0.4
        }, {
          percentile: 20,
          value: 0.38
        }, {
          percentile: 10,
          value: 0.33
        }]
      }
    ]
  }
];