import { MeasurePercentiles } from "../model";

export const GreasyPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 7.1
        }, {
          percentile: 80,
          value: 9.4
        }, {
          percentile: 70,
          value: 11.8
        }, {
          percentile: 60,
          value: 14.1
        }, {
          percentile: 50,
          value: 15.9
        }, {
          percentile: 40,
          value: 17.4
        }, {
          percentile: 30,
          value: 19.5
        }, {
          percentile: 20,
          value: 22.4
        }, {
          percentile: 10,
          value: 25.9
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 11.3
        }, {
          percentile: 80,
          value: 13.9
        }, {
          percentile: 70,
          value: 15.9
        }, {
          percentile: 60,
          value: 17.5
        }, {
          percentile: 50,
          value: 19
        }, {
          percentile: 40,
          value: 20.5
        }, {
          percentile: 30,
          value: 22.3
        }, {
          percentile: 20,
          value: 24.2
        }, {
          percentile: 10,
          value: 27.3
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 13.6
        }, {
          percentile: 80,
          value: 16.3
        }, {
          percentile: 70,
          value: 18.1
        }, {
          percentile: 60,
          value: 19.6
        }, {
          percentile: 50,
          value: 21.1
        }, {
          percentile: 40,
          value: 22.5
        }, {
          percentile: 30,
          value: 24.1
        }, {
          percentile: 20,
          value: 26.1
        }, {
          percentile: 10,
          value: 28.9
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 15.3
        }, {
          percentile: 80,
          value: 17.9
        }, {
          percentile: 70,
          value: 19.8
        }, {
          percentile: 60,
          value: 21.3
        }, {
          percentile: 50,
          value: 22.7
        }, {
          percentile: 40,
          value: 24.1
        }, {
          percentile: 30,
          value: 25.7
        }, {
          percentile: 20,
          value: 27.5
        }, {
          percentile: 10,
          value: 30.3
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 15.3
        }, {
          percentile: 80,
          value: 18.4
        }, {
          percentile: 70,
          value: 20.3
        }, {
          percentile: 60,
          value: 22
        }, {
          percentile: 50,
          value: 23.5
        }, {
          percentile: 40,
          value: 25
        }, {
          percentile: 30,
          value: 26.7
        }, {
          percentile: 20,
          value: 28.5
        }, {
          percentile: 10,
          value: 31.2
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 14.5
        }, {
          percentile: 80,
          value: 17.1
        }, {
          percentile: 70,
          value: 19
        }, {
          percentile: 60,
          value: 20.6
        }, {
          percentile: 50,
          value: 22.1
        }, {
          percentile: 40,
          value: 23.7
        }, {
          percentile: 30,
          value: 25.4
        }, {
          percentile: 20,
          value: 27.7
        }, {
          percentile: 10,
          value: 32.1
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 15.5
        }, {
          percentile: 80,
          value: 18
        }, {
          percentile: 70,
          value: 20
        }, {
          percentile: 60,
          value: 21.6
        }, {
          percentile: 50,
          value: 23.1
        }, {
          percentile: 40,
          value: 24.9
        }, {
          percentile: 30,
          value: 27
        }, {
          percentile: 20,
          value: 28.3
        }, {
          percentile: 10,
          value: 32.8
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 18.5
        }, {
          percentile: 80,
          value: 21.3
        }, {
          percentile: 70,
          value: 23.5
        }, {
          percentile: 60,
          value: 24.9
        }, {
          percentile: 50,
          value: 26.4
        }, {
          percentile: 40,
          value: 28.1
        }, {
          percentile: 30,
          value: 30.1
        }, {
          percentile: 20,
          value: 32.1
        }, {
          percentile: 10,
          value: 35
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 21.6
        }, {
          percentile: 80,
          value: 25
        }, {
          percentile: 70,
          value: 26.6
        }, {
          percentile: 60,
          value: 28.5
        }, {
          percentile: 50,
          value: 30.1
        }, {
          percentile: 40,
          value: 31.6
        }, {
          percentile: 30,
          value: 33.5
        }, {
          percentile: 20,
          value: 35.6
        }, {
          percentile: 10,
          value: 31.9
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 21.1
        }, {
          percentile: 80,
          value: 25.1
        }, {
          percentile: 70,
          value: 27.5
        }, {
          percentile: 60,
          value: 29.3
        }, {
          percentile: 50,
          value: 30.9
        }, {
          percentile: 40,
          value: 32.5
        }, {
          percentile: 30,
          value: 34.3
        }, {
          percentile: 20,
          value: 36.6
        }, {
          percentile: 10,
          value: 39.3
        }]
      }
    ]
  }
];