import { MeasurePercentiles } from "../model";

export const PushUpsPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 41
        }, {
          percentile: 80,
          value: 34
        }, {
          percentile: 70,
          value: 30
        }, {
          percentile: 60,
          value: 27
        }, {
          percentile: 50,
          value: 24
        }, {
          percentile: 40,
          value: 21
        }, {
          percentile: 30,
          value: 18
        }, {
          percentile: 20,
          value: 16
        }, {
          percentile: 10,
          value: 11
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 32
        }, {
          percentile: 80,
          value: 27
        }, {
          percentile: 70,
          value: 24
        }, {
          percentile: 60,
          value: 21
        }, {
          percentile: 50,
          value: 19
        }, {
          percentile: 40,
          value: 16
        }, {
          percentile: 30,
          value: 14
        }, {
          percentile: 20,
          value: 11
        }, {
          percentile: 10,
          value: 8
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 25
        }, {
          percentile: 80,
          value: 21
        }, {
          percentile: 70,
          value: 19
        }, {
          percentile: 60,
          value: 16
        }, {
          percentile: 50,
          value: 13
        }, {
          percentile: 40,
          value: 12
        }, {
          percentile: 30,
          value: 10
        }, {
          percentile: 20,
          value: 8
        }, {
          percentile: 10,
          value: 5
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 24
        }, {
          percentile: 80,
          value: 17
        }, {
          percentile: 70,
          value: 14
        }, {
          percentile: 60,
          value: 11
        }, {
          percentile: 50,
          value: 10
        }, {
          percentile: 40,
          value: 9
        }, {
          percentile: 30,
          value: 7
        }, {
          percentile: 20,
          value: 5
        }, {
          percentile: 10,
          value: 4
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 24
        }, {
          percentile: 80,
          value: 16
        }, {
          percentile: 70,
          value: 11
        }, {
          percentile: 60,
          value: 10
        }, {
          percentile: 50,
          value: 9
        }, {
          percentile: 40,
          value: 7
        }, {
          percentile: 30,
          value: 6
        }, {
          percentile: 20,
          value: 4
        }, {
          percentile: 10,
          value: 2
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 32
        }, {
          percentile: 80,
          value: 26
        }, {
          percentile: 70,
          value: 22
        }, {
          percentile: 60,
          value: 20
        }, {
          percentile: 50,
          value: 16
        }, {
          percentile: 40,
          value: 14
        }, {
          percentile: 30,
          value: 11
        }, {
          percentile: 20,
          value: 9
        }, {
          percentile: 10,
          value: 5
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 31
        }, {
          percentile: 80,
          value: 24
        }, {
          percentile: 70,
          value: 21
        }, {
          percentile: 60,
          value: 17
        }, {
          percentile: 50,
          value: 14
        }, {
          percentile: 40,
          value: 12
        }, {
          percentile: 30,
          value: 10
        }, {
          percentile: 20,
          value: 7
        }, {
          percentile: 10,
          value: 4
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 28
        }, {
          percentile: 80,
          value: 22
        }, {
          percentile: 70,
          value: 18
        }, {
          percentile: 60,
          value: 14
        }, {
          percentile: 50,
          value: 12
        }, {
          percentile: 40,
          value: 10
        }, {
          percentile: 30,
          value: 7
        }, {
          percentile: 20,
          value: 4
        }, {
          percentile: 10,
          value: 2
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 23
        }, {
          percentile: 80,
          value: 17
        }, {
          percentile: 70,
          value: 13
        }, {
          percentile: 60,
          value: 10
        }, {
          percentile: 50,
          value: 9
        }, {
          percentile: 40,
          value: 7
        }, {
          percentile: 30,
          value: 6
        }, {
          percentile: 20,
          value: 4
        }, {
          percentile: 10,
          value: 2
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 25
        }, {
          percentile: 80,
          value: 15
        }, {
          percentile: 70,
          value: 12
        }, {
          percentile: 60,
          value: 10
        }, {
          percentile: 50,
          value: 6
        }, {
          percentile: 40,
          value: 4
        }, {
          percentile: 30,
          value: 2
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: 0
        }]
      }
    ]
  }
];