import { MeasurePercentiles } from "../model";

export const AbsPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 75
        }, {
          percentile: 80,
          value: 56
        }, {
          percentile: 70,
          value: 41
        }, {
          percentile: 60,
          value: 31
        }, {
          percentile: 50,
          value: 27
        }, {
          percentile: 40,
          value: 24
        }, {
          percentile: 30,
          value: 20
        }, {
          percentile: 20,
          value: 13
        }, {
          percentile: 10,
          value: 4
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 75
        }, {
          percentile: 80,
          value: 69
        }, {
          percentile: 70,
          value: 46
        }, {
          percentile: 60,
          value: 36
        }, {
          percentile: 50,
          value: 31
        }, {
          percentile: 40,
          value: 26
        }, {
          percentile: 30,
          value: 19
        }, {
          percentile: 20,
          value: 13
        }, {
          percentile: 10,
          value: 0
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 75
        }, {
          percentile: 80,
          value: 75
        }, {
          percentile: 70,
          value: 67
        }, {
          percentile: 60,
          value: 51
        }, {
          percentile: 50,
          value: 39
        }, {
          percentile: 40,
          value: 31
        }, {
          percentile: 30,
          value: 26
        }, {
          percentile: 20,
          value: 21
        }, {
          percentile: 10,
          value: 13
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 74
        }, {
          percentile: 80,
          value: 60
        }, {
          percentile: 70,
          value: 45
        }, {
          percentile: 60,
          value: 35
        }, {
          percentile: 50,
          value: 27
        }, {
          percentile: 40,
          value: 23
        }, {
          percentile: 30,
          value: 19
        }, {
          percentile: 20,
          value: 13
        }, {
          percentile: 10,
          value: 0
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 53
        }, {
          percentile: 80,
          value: 33
        }, {
          percentile: 70,
          value: 26
        }, {
          percentile: 60,
          value: 19
        }, {
          percentile: 50,
          value: 16
        }, {
          percentile: 40,
          value: 9
        }, {
          percentile: 30,
          value: 6
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: 0
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 70
        }, {
          percentile: 80,
          value: 45
        }, {
          percentile: 70,
          value: 37
        }, {
          percentile: 60,
          value: 32
        }, {
          percentile: 50,
          value: 27
        }, {
          percentile: 40,
          value: 21
        }, {
          percentile: 30,
          value: 17
        }, {
          percentile: 20,
          value: 12
        }, {
          percentile: 10,
          value: 5
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 55
        }, {
          percentile: 80,
          value: 43
        }, {
          percentile: 70,
          value: 34
        }, {
          percentile: 60,
          value: 28
        }, {
          percentile: 50,
          value: 21
        }, {
          percentile: 40,
          value: 15
        }, {
          percentile: 30,
          value: 12
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: 0
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 50
        }, {
          percentile: 80,
          value: 42
        }, {
          percentile: 70,
          value: 33
        }, {
          percentile: 60,
          value: 28
        }, {
          percentile: 50,
          value: 25
        }, {
          percentile: 40,
          value: 20
        }, {
          percentile: 30,
          value: 14
        }, {
          percentile: 20,
          value: 5
        }, {
          percentile: 10,
          value: 0
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 48
        }, {
          percentile: 80,
          value: 30
        }, {
          percentile: 70,
          value: 23
        }, {
          percentile: 60,
          value: 16
        }, {
          percentile: 50,
          value: 9
        }, {
          percentile: 40,
          value: 2
        }, {
          percentile: 30,
          value: 0
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: 0
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 50
        }, {
          percentile: 80,
          value: 30
        }, {
          percentile: 70,
          value: 24
        }, {
          percentile: 60,
          value: 19
        }, {
          percentile: 50,
          value: 13
        }, {
          percentile: 40,
          value: 9
        }, {
          percentile: 30,
          value: 3
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: 0
        }]
      }
    ]
  }
];