import { MeasurePercentiles } from "../model";

export const LegPressPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 2.27
        }, {
          percentile: 80,
          value: 2.13
        }, {
          percentile: 70,
          value: 2.05
        }, {
          percentile: 60,
          value: 1.97
        }, {
          percentile: 50,
          value: 1.91
        }, {
          percentile: 40,
          value: 1.83
        }, {
          percentile: 30,
          value: 1.74
        }, {
          percentile: 20,
          value: 1.63
        }, {
          percentile: 10,
          value: 1.51
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 2.07
        }, {
          percentile: 80,
          value: 1.93
        }, {
          percentile: 70,
          value: 1.85
        }, {
          percentile: 60,
          value: 1.77
        }, {
          percentile: 50,
          value: 1.71
        }, {
          percentile: 40,
          value: 1.65
        }, {
          percentile: 30,
          value: 1.59
        }, {
          percentile: 20,
          value: 1.52
        }, {
          percentile: 10,
          value: 1.43
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 1.92
        }, {
          percentile: 80,
          value: 1.82
        }, {
          percentile: 70,
          value: 1.74
        }, {
          percentile: 60,
          value: 1.68
        }, {
          percentile: 50,
          value: 1.62
        }, {
          percentile: 40,
          value: 1.57
        }, {
          percentile: 30,
          value: 1.51
        }, {
          percentile: 20,
          value: 1.44
        }, {
          percentile: 10,
          value: 1.35
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 1.8
        }, {
          percentile: 80,
          value: 1.71
        }, {
          percentile: 70,
          value: 1.64
        }, {
          percentile: 60,
          value: 1.58
        }, {
          percentile: 50,
          value: 1.52
        }, {
          percentile: 40,
          value: 1.46
        }, {
          percentile: 30,
          value: 1.39
        }, {
          percentile: 20,
          value: 1.32
        }, {
          percentile: 10,
          value: 1.22
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 1.73
        }, {
          percentile: 80,
          value: 1.62
        }, {
          percentile: 70,
          value: 1.56
        }, {
          percentile: 60,
          value: 1.49
        }, {
          percentile: 50,
          value: 1.43
        }, {
          percentile: 40,
          value: 1.38
        }, {
          percentile: 30,
          value: 1.3
        }, {
          percentile: 20,
          value: 1.25
        }, {
          percentile: 10,
          value: 1.16
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 1.82
        }, {
          percentile: 80,
          value: 1.68
        }, {
          percentile: 70,
          value: 1.58
        }, {
          percentile: 60,
          value: 1.5
        }, {
          percentile: 50,
          value: 1.44
        }, {
          percentile: 40,
          value: 1.37
        }, {
          percentile: 30,
          value: 1.27
        }, {
          percentile: 20,
          value: 1.22
        }, {
          percentile: 10,
          value: 1.14
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 1.61
        }, {
          percentile: 80,
          value: 1.47
        }, {
          percentile: 70,
          value: 1.39
        }, {
          percentile: 60,
          value: 1.33
        }, {
          percentile: 50,
          value: 1.27
        }, {
          percentile: 40,
          value: 1.21
        }, {
          percentile: 30,
          value: 1.15
        }, {
          percentile: 20,
          value: 1.09
        }, {
          percentile: 10,
          value: 1
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 1.48
        }, {
          percentile: 80,
          value: 1.37
        }, {
          percentile: 70,
          value: 1.29
        }, {
          percentile: 60,
          value: 1.23
        }, {
          percentile: 50,
          value: 1.18
        }, {
          percentile: 40,
          value: 1.13
        }, {
          percentile: 30,
          value: 1.08
        }, {
          percentile: 20,
          value: 1.03
        }, {
          percentile: 10,
          value: 0.94
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 1.37
        }, {
          percentile: 80,
          value: 1.25
        }, {
          percentile: 70,
          value: 1.17
        }, {
          percentile: 60,
          value: 1.1
        }, {
          percentile: 50,
          value: 1.05
        }, {
          percentile: 40,
          value: 0.99
        }, {
          percentile: 30,
          value: 0.95
        }, {
          percentile: 20,
          value: 0.88
        }, {
          percentile: 10,
          value: 0.78
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 1.32
        }, {
          percentile: 80,
          value: 1.18
        }, {
          percentile: 70,
          value: 1.13
        }, {
          percentile: 60,
          value: 1.04
        }, {
          percentile: 50,
          value: 0.99
        }, {
          percentile: 40,
          value: 0.93
        }, {
          percentile: 30,
          value: 0.88
        }, {
          percentile: 20,
          value: 0.85
        }, {
          percentile: 10,
          value: 0.72
        }]
      }
    ]
  }
];