import { MeasurePercentiles } from "../model";

export const SitNReachPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 40
        }, {
          percentile: 80,
          value: 39
        }, {
          percentile: 70,
          value: 34
        }, {
          percentile: 60,
          value: 33
        }, {
          percentile: 50,
          value: 30
        }, {
          percentile: 40,
          value: 29
        }, {
          percentile: 30,
          value: 25
        }, {
          percentile: 20,
          value: 24
        }, {
          percentile: 10,
          value: 18
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 38
        }, {
          percentile: 80,
          value: 37
        }, {
          percentile: 70,
          value: 33
        }, {
          percentile: 60,
          value: 32
        }, {
          percentile: 50,
          value: 28
        }, {
          percentile: 40,
          value: 27
        }, {
          percentile: 30,
          value: 23
        }, {
          percentile: 20,
          value: 22
        }, {
          percentile: 10,
          value: 17
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 35
        }, {
          percentile: 80,
          value: 34
        }, {
          percentile: 70,
          value: 29
        }, {
          percentile: 60,
          value: 28
        }, {
          percentile: 50,
          value: 24
        }, {
          percentile: 40,
          value: 23
        }, {
          percentile: 30,
          value: 18
        }, {
          percentile: 20,
          value: 17
        }, {
          percentile: 10,
          value: 12
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 35
        }, {
          percentile: 80,
          value: 34
        }, {
          percentile: 70,
          value: 28
        }, {
          percentile: 60,
          value: 27
        }, {
          percentile: 50,
          value: 24
        }, {
          percentile: 40,
          value: 23
        }, {
          percentile: 30,
          value: 16
        }, {
          percentile: 20,
          value: 15
        }, {
          percentile: 10,
          value: 12
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 33
        }, {
          percentile: 80,
          value: 32
        }, {
          percentile: 70,
          value: 25
        }, {
          percentile: 60,
          value: 24
        }, {
          percentile: 50,
          value: 20
        }, {
          percentile: 40,
          value: 19
        }, {
          percentile: 30,
          value: 15
        }, {
          percentile: 20,
          value: 14
        }, {
          percentile: 10,
          value: 11
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 43
        }, {
          percentile: 80,
          value: 40
        }, {
          percentile: 70,
          value: 37
        }, {
          percentile: 60,
          value: 36
        }, {
          percentile: 50,
          value: 33
        }, {
          percentile: 40,
          value: 32
        }, {
          percentile: 30,
          value: 28
        }, {
          percentile: 20,
          value: 27
        }, {
          percentile: 10,
          value: 22
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 41
        }, {
          percentile: 80,
          value: 40
        }, {
          percentile: 70,
          value: 36
        }, {
          percentile: 60,
          value: 35
        }, {
          percentile: 50,
          value: 32
        }, {
          percentile: 40,
          value: 31
        }, {
          percentile: 30,
          value: 27
        }, {
          percentile: 20,
          value: 26
        }, {
          percentile: 10,
          value: 21
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 40
        }, {
          percentile: 80,
          value: 37
        }, {
          percentile: 70,
          value: 34
        }, {
          percentile: 60,
          value: 33
        }, {
          percentile: 50,
          value: 30
        }, {
          percentile: 40,
          value: 29
        }, {
          percentile: 30,
          value: 25
        }, {
          percentile: 20,
          value: 24
        }, {
          percentile: 10,
          value: 19
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 39
        }, {
          percentile: 80,
          value: 38
        }, {
          percentile: 70,
          value: 33
        }, {
          percentile: 60,
          value: 32
        }, {
          percentile: 50,
          value: 30
        }, {
          percentile: 40,
          value: 29
        }, {
          percentile: 30,
          value: 25
        }, {
          percentile: 20,
          value: 24
        }, {
          percentile: 10,
          value: 19
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 35
        }, {
          percentile: 80,
          value: 34
        }, {
          percentile: 70,
          value: 31
        }, {
          percentile: 60,
          value: 30
        }, {
          percentile: 50,
          value: 27
        }, {
          percentile: 40,
          value: 26
        }, {
          percentile: 30,
          value: 23
        }, {
          percentile: 20,
          value: 22
        }, {
          percentile: 10,
          value: 18
        }]
      }
    ]
  }
];