import { MeasurePercentiles } from "../model";

export const SitNReachPercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 16
        }, {
          percentile: 80,
          value: 12
        }, {
          percentile: 70,
          value: 10
        }, {
          percentile: 60,
          value: 7
        }, {
          percentile: 50,
          value: 5
        }, {
          percentile: 40,
          value: 3
        }, {
          percentile: 30,
          value: 0
        }, {
          percentile: 20,
          value: -3
        }, {
          percentile: 10,
          value: -8
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 14
        }, {
          percentile: 80,
          value: 11
        }, {
          percentile: 70,
          value: 8
        }, {
          percentile: 60,
          value: 6
        }, {
          percentile: 50,
          value: 3
        }, {
          percentile: 40,
          value: 1
        }, {
          percentile: 30,
          value: -2
        }, {
          percentile: 20,
          value: -5
        }, {
          percentile: 10,
          value: -9
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 11
        }, {
          percentile: 80,
          value: 8
        }, {
          percentile: 70,
          value: 4
        }, {
          percentile: 60,
          value: 2
        }, {
          percentile: 50,
          value: -1
        }, {
          percentile: 40,
          value: -3
        }, {
          percentile: 30,
          value: -6
        }, {
          percentile: 20,
          value: -10
        }, {
          percentile: 10,
          value: -14
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 12
        }, {
          percentile: 80,
          value: 6
        }, {
          percentile: 70,
          value: 3
        }, {
          percentile: 60,
          value: 1
        }, {
          percentile: 50,
          value: -1
        }, {
          percentile: 40,
          value: -4
        }, {
          percentile: 30,
          value: -8
        }, {
          percentile: 20,
          value: -11
        }, {
          percentile: 10,
          value: -14
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 9
        }, {
          percentile: 80,
          value: 4
        }, {
          percentile: 70,
          value: 0
        }, {
          percentile: 60,
          value: -2
        }, {
          percentile: 50,
          value: -4
        }, {
          percentile: 40,
          value: -8
        }, {
          percentile: 30,
          value: -10
        }, {
          percentile: 20,
          value: -12
        }, {
          percentile: 10,
          value: -15
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 17
        }, {
          percentile: 80,
          value: 14
        }, {
          percentile: 70,
          value: 12
        }, {
          percentile: 60,
          value: 10
        }, {
          percentile: 50,
          value: 8
        }, {
          percentile: 40,
          value: 6
        }, {
          percentile: 30,
          value: 3
        }, {
          percentile: 20,
          value: 0
        }, {
          percentile: 10,
          value: -4
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 16
        }, {
          percentile: 80,
          value: 13
        }, {
          percentile: 70,
          value: 11
        }, {
          percentile: 60,
          value: 9
        }, {
          percentile: 50,
          value: 7
        }, {
          percentile: 40,
          value: 5
        }, {
          percentile: 30,
          value: 2
        }, {
          percentile: 20,
          value: -1
        }, {
          percentile: 10,
          value: -5
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 14
        }, {
          percentile: 80,
          value: 11
        }, {
          percentile: 70,
          value: 9
        }, {
          percentile: 60,
          value: 7
        }, {
          percentile: 50,
          value: 5
        }, {
          percentile: 40,
          value: 3
        }, {
          percentile: 30,
          value: 0
        }, {
          percentile: 20,
          value: -2
        }, {
          percentile: 10,
          value: -7
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 14
        }, {
          percentile: 80,
          value: 11
        }, {
          percentile: 70,
          value: 9
        }, {
          percentile: 60,
          value: 6
        }, {
          percentile: 50,
          value: 4
        }, {
          percentile: 40,
          value: 3
        }, {
          percentile: 30,
          value: 0
        }, {
          percentile: 20,
          value: -3
        }, {
          percentile: 10,
          value: -7
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 11
        }, {
          percentile: 80,
          value: 8
        }, {
          percentile: 70,
          value: 5
        }, {
          percentile: 60,
          value: 4
        }, {
          percentile: 50,
          value: 2
        }, {
          percentile: 40,
          value: 0
        }, {
          percentile: 30,
          value: -2
        }, {
          percentile: 20,
          value: -3
        }, {
          percentile: 10,
          value: -8
        }]
      }
    ]
  }
];