import { MeasurePercentiles } from "../model";

export const Vo2PercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 55.5
        }, {
          percentile: 80,
          value: 51.4
        }, {
          percentile: 70,
          value: 47.9
        }, {
          percentile: 60,
          value: 44.5
        }, {
          percentile: 50,
          value: 41.9
        }, {
          percentile: 40,
          value: 38.3
        }, {
          percentile: 30,
          value: 36.2
        }, {
          percentile: 20,
          value: 33.2
        }, {
          percentile: 10,
          value: 29.5
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 41.7
        }, {
          percentile: 80,
          value: 36.2
        }, {
          percentile: 70,
          value: 33.9
        }, {
          percentile: 60,
          value: 31.1
        }, {
          percentile: 50,
          value: 30.1
        }, {
          percentile: 40,
          value: 28.1
        }, {
          percentile: 30,
          value: 26.9
        }, {
          percentile: 20,
          value: 25.4
        }, {
          percentile: 10,
          value: 21.8
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 37.1
        }, {
          percentile: 80,
          value: 34.2
        }, {
          percentile: 70,
          value: 30.4
        }, {
          percentile: 60,
          value: 28.6
        }, {
          percentile: 50,
          value: 27.1
        }, {
          percentile: 40,
          value: 25.4
        }, {
          percentile: 30,
          value: 24
        }, {
          percentile: 20,
          value: 22.2
        }, {
          percentile: 10,
          value: 20.6
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 34
        }, {
          percentile: 80,
          value: 30.7
        }, {
          percentile: 70,
          value: 28.2
        }, {
          percentile: 60,
          value: 26.3
        }, {
          percentile: 50,
          value: 24.8
        }, {
          percentile: 40,
          value: 23.6
        }, {
          percentile: 30,
          value: 22.6
        }, {
          percentile: 20,
          value: 21.5
        }, {
          percentile: 10,
          value: 20.4
        }]
      }, {
        lower: 60,
        higher: 69,
        percentiles: [{
          percentile: 90,
          value: 29.9
        }, {
          percentile: 80,
          value: 26.7
        }, {
          percentile: 70,
          value: 24.5
        }, {
          percentile: 60,
          value: 23.2
        }, {
          percentile: 50,
          value: 22.4
        }, {
          percentile: 40,
          value: 21.4
        }, {
          percentile: 30,
          value: 20.2
        }, {
          percentile: 20,
          value: 19
        }, {
          percentile: 10,
          value: 17.3
        }]
      }, {
        lower: 70,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 28.1
        }, {
          percentile: 80,
          value: 24.5
        }, {
          percentile: 70,
          value: 21.9
        }, {
          percentile: 60,
          value: 20.4
        }, {
          percentile: 50,
          value: 19.5
        }, {
          percentile: 40,
          value: 18.5
        }, {
          percentile: 30,
          value: 17.5
        }, {
          percentile: 20,
          value: 16.7
        }, {
          percentile: 10,
          value: 15.8
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 42.6
        }, {
          percentile: 80,
          value: 38.8
        }, {
          percentile: 70,
          value: 35.6
        }, {
          percentile: 60,
          value: 33.6
        }, {
          percentile: 50,
          value: 31
        }, {
          percentile: 40,
          value: 28.1
        }, {
          percentile: 30,
          value: 25.6
        }, {
          percentile: 20,
          value: 21.6
        }, {
          percentile: 10,
          value: 19.3
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 30
        }, {
          percentile: 80,
          value: 26
        }, {
          percentile: 70,
          value: 24.2
        }, {
          percentile: 60,
          value: 22.5
        }, {
          percentile: 50,
          value: 21.6
        }, {
          percentile: 40,
          value: 20.1
        }, {
          percentile: 30,
          value: 18.8
        }, {
          percentile: 20,
          value: 17
        }, {
          percentile: 10,
          value: 15.9
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 26.2
        }, {
          percentile: 80,
          value: 23.4
        }, {
          percentile: 70,
          value: 22
        }, {
          percentile: 60,
          value: 20.7
        }, {
          percentile: 50,
          value: 19.4
        }, {
          percentile: 40,
          value: 18.4
        }, {
          percentile: 30,
          value: 17.1
        }, {
          percentile: 20,
          value: 15.8
        }, {
          percentile: 10,
          value: 14.6
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 22.6
        }, {
          percentile: 80,
          value: 20.7
        }, {
          percentile: 70,
          value: 19.3
        }, {
          percentile: 60,
          value: 18.2
        }, {
          percentile: 50,
          value: 17.3
        }, {
          percentile: 40,
          value: 16.6
        }, {
          percentile: 30,
          value: 15.7
        }, {
          percentile: 20,
          value: 14.9
        }, {
          percentile: 10,
          value: 13.7
        }]
      }, {
        lower: 60,
        higher: 69,
        percentiles: [{
          percentile: 90,
          value: 20.5
        }, {
          percentile: 80,
          value: 18.8
        }, {
          percentile: 70,
          value: 17.8
        }, {
          percentile: 60,
          value: 16.7
        }, {
          percentile: 50,
          value: 16
        }, {
          percentile: 40,
          value: 15.4
        }, {
          percentile: 30,
          value: 14.7
        }, {
          percentile: 20,
          value: 14
        }, {
          percentile: 10,
          value: 13
        }]
      }, {
        lower: 70,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 18
        }, {
          percentile: 80,
          value: 16.9
        }, {
          percentile: 70,
          value: 16.1
        }, {
          percentile: 60,
          value: 15.4
        }, {
          percentile: 50,
          value: 14.8
        }, {
          percentile: 40,
          value: 14.2
        }, {
          percentile: 30,
          value: 13.6
        }, {
          percentile: 20,
          value: 12.8
        }, {
          percentile: 10,
          value: 12
        }]
      }
    ]
  }
];