import { MeasurePercentiles } from "../model";

export const Vo2PercentilesValues: MeasurePercentiles[]  =[
  {
    gender: 'male',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 51.4
        }, {
          percentile: 80,
          value: 48.2
        }, {
          percentile: 70,
          value: 46.8
        }, {
          percentile: 60,
          value: 44.2
        }, {
          percentile: 50,
          value: 42.5
        }, {
          percentile: 40,
          value: 41
        }, {
          percentile: 30,
          value: 39.5
        }, {
          percentile: 20,
          value: 37.1
        }, {
          percentile: 10,
          value: 34.5
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 50.4
        }, {
          percentile: 80,
          value: 46.8
        }, {
          percentile: 70,
          value: 44.6
        }, {
          percentile: 60,
          value: 42.4
        }, {
          percentile: 50,
          value: 41
        }, {
          percentile: 40,
          value: 38.9
        }, {
          percentile: 30,
          value: 37.4
        }, {
          percentile: 20,
          value: 35.4
        }, {
          percentile: 10,
          value: 32.5
        }]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 48.2
        }, {
          percentile: 80,
          value: 44.1
        }, {
          percentile: 70,
          value: 41.8
        }, {
          percentile: 60,
          value: 39.9
        }, {
          percentile: 50,
          value: 38.1
        }, {
          percentile: 40,
          value: 36.7
        }, {
          percentile: 30,
          value: 35.1
        }, {
          percentile: 20,
          value: 33
        }, {
          percentile: 10,
          value: 30.9
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 45.3
        }, {
          percentile: 80,
          value: 41
        }, {
          percentile: 70,
          value: 38.1
        }, {
          percentile: 60,
          value: 36.7
        }, {
          percentile: 50,
          value: 35.2
        }, {
          percentile: 40,
          value: 33.8
        }, {
          percentile: 30,
          value: 32.3
        }, {
          percentile: 20,
          value: 30.2
        }, {
          percentile: 10,
          value: 28
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 42.5
        }, {
          percentile: 80,
          value: 38.1
        }, {
          percentile: 70,
          value: 35.3
        }, {
          percentile: 60,
          value: 33.6
        }, {
          percentile: 50,
          value: 31.8
        }, {
          percentile: 40,
          value: 30.2
        }, {
          percentile: 30,
          value: 28.7
        }, {
          percentile: 20,
          value: 26.5
        }, {
          percentile: 10,
          value: 23.1
        }]
      }
    ]
  }, 
  {
    gender: 'female',
    ageRange: [
      {
        lower: 20,
        higher: 29,
        percentiles: [{
          percentile: 90,
          value: 44
        }, {
          percentile: 80,
          value: 41
        }, {
          percentile: 70,
          value: 38
        }, {
          percentile: 60,
          value: 37
        }, {
          percentile: 50,
          value: 35
        }, {
          percentile: 40,
          value: 34
        }, {
          percentile: 30,
          value: 32
        }, {
          percentile: 20,
          value: 31
        }, {
          percentile: 10,
          value: 28
        }]
      }, {
        lower: 30,
        higher: 39,
        percentiles: [{
          percentile: 90,
          value: 41
        }, {
          percentile: 80,
          value: 39
        }, {
          percentile: 70,
          value: 37
        }, {
          percentile: 60,
          value: 35
        }, {
          percentile: 50,
          value: 34
        }, {
          percentile: 40,
          value: 32
        }, {
          percentile: 30,
          value: 31
        }, {
          percentile: 20,
          value: 29
        }, {
          percentile: 10,
          value: 27
        }
      ]
      }, {
        lower: 40,
        higher: 49,
        percentiles: [{
          percentile: 90,
          value: 40
        }, {
          percentile: 80,
          value: 36
        }, {
          percentile: 70,
          value: 34
        }, {
          percentile: 60,
          value: 32
        }, {
          percentile: 50,
          value: 31
        }, {
          percentile: 40,
          value: 30
        }, {
          percentile: 30,
          value: 28
        }, {
          percentile: 20,
          value: 27
        }, {
          percentile: 10,
          value: 25
        }]
      }, {
        lower: 50,
        higher: 59,
        percentiles: [{
          percentile: 90,
          value: 35
        }, {
          percentile: 80,
          value: 32
        }, {
          percentile: 70,
          value: 31
        }, {
          percentile: 60,
          value: 29
        }, {
          percentile: 50,
          value: 28
        }, {
          percentile: 40,
          value: 27
        }, {
          percentile: 30,
          value: 26
        }, {
          percentile: 20,
          value: 24
        }, {
          percentile: 10,
          value: 22
        }]
      }, {
        lower: 60,
        higher: 200,
        percentiles: [{
          percentile: 90,
          value: 35
        }, {
          percentile: 80,
          value: 31
        }, {
          percentile: 70,
          value: 29
        }, {
          percentile: 60,
          value: 27
        }, {
          percentile: 50,
          value: 26
        }, {
          percentile: 40,
          value: 25
        }, {
          percentile: 30,
          value: 24
        }, {
          percentile: 20,
          value: 23
        }, {
          percentile: 10,
          value: 21
        }]
      }
    ]
  }
];